# Generated by Django 4.0.1 on 2022-06-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
