# Generated by Django 4.0.1 on 2022-06-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
