# Generated by Django 4.0.1 on 2022-06-09 05:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_product_zip_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checkout',
            new_name='CheckoutAddress',
        ),
    ]
